thread 'main' panicked at src/main.rs:33:10:
Cannot run migration: Execute(Database(PgDatabaseError { severity: Error, code: "42703", message: "column \"task_type\" does not exist", detail: None, hint: None, position: None, where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("indexcmds.c"), line: Some(1884), routine: Some("ComputeIndexAttrs") }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
